language: node_js
sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh  | bash
  - export PATH=$HOME/.yarn/bin:$PATH

node_js:
  - '6.6.0'

env:
  matrix:
    # Order: a slower build first, so that we don't occupy an idle travis worker waiting for others to complete.
   - CI_MODE=normal

install:
  - ./scripts/ci/install.sh

script:
  - ./scripts/ci/build.sh && ./scripts/ci/test.sh

after_script:
  - ./scripts/ci/cleanup.sh
