language: node_js
sudo: false

node_js:
  - '10.16.3'

env:
  matrix:
    # Order: a slower build first, so that we don't occupy an idle travis worker waiting for others to complete.
   - CI_MODE=normal

install:
  - ./scripts/install.sh

script:
  - ./scripts/lint.sh
  - ./scripts/build.sh
  - ./scripts/test.sh
  - ./scripts/format.sh

after_script:
  - ./scripts/cleanup.sh

deploy:
  provider: releases
  api_key:
    # Use the mary-poppins account to deploy to github
    secure: kCDrgryIYejYfnbQj8oLV7ciDW+QfGU3xcAf1H63Xippdbux0S5QP0iCXRKq7kFf2xRQGCu6paouQytz3uhO9ZJ6u+QBrmGh6KnTuwlQT7ldZUbv9I0lXC4XNhaNogAQ/N4vDO62Nx3H07Gx9+t68b81ecrle4YF9y2EABeJ7XywaRDz5pUNOZHA9hWresuQjJw3BBetzC4WhXCdUNGgg55+zaq+DypM2uTfyv1DDHMNpPlXpEZ9zTYJaDWDjVFE5wny7dWXQLfxAl0mZkEtOF/EV+ns2MEVkjj3Kv0U0iMTRGQPvMSWimOoAqCScJFCqvV65/3RoXEugcqzsf3nMhi9pS0fbBS8dNfzmi9r/lHlqu7bxtMeUy616cgsmBz58WiPE/ZO4YH1LNwKfnJufwAy4FzqbM7h+PSNgJ0TDbf9Is6kcIecygkJJPffBziafoiS8bIi5pYjSKKQ8TfwUIK0FPugQ/Qk6kTD490F3EbBm7WT+G3XRQFd3WKk0v+0RdHKDo5pEb6GC9WYSt8lvL2FjY62wCg4BCZ05BU3acJ+w079gBihWXMO6J0CZVUWF3T7oOyoMXAkAA9xv8WJeDQoknUAKrnvXaG5rLs39iEvS7laiinMUs3NwXhnia5MbO36HpgzT16pxQvIqu9V7nDOa0eVJj4MDoNdQUsXMCc=
  skip_cleanup: true
  file: dist/ngls.vsix
  on:
    repo: angular/vscode-ng-language-service
    tags: true
